### PR TITLE
l/list-migrations: (optionally) initialize a JDBC driver

### PR DESCRIPTION
**Pull request by alandipert**
This is great, thanks!  I had a small problem that this PR fixes - it provides a way for the user to initialize the JDBC driver inside the ragtime pod.

### CODE REVIEW

**Comment by alandipert** [comment]
Example usage:

```
boot ragtime -m -d "jdbc:postgresql://.." -c org.postgresql.Driver
```

**Comment by mbuczko** [comment]
I noticed that problem as well few days ago but didn't have a time to look why it happened. Thanks a lot for solving it!

**Comment by alandipert** [comment]
No problem :smile: Would you be open to releasing a non-snapshot?

**Comment by mbuczko** [comment]
sure, I'll release 0.1.1 tomorrow morning (I don't have my PGP key with me right now to sign up the jar)

**Comment by alandipert** [comment]
Sounds awesome, thanks!

**Comment by mbuczko** [comment]
done.

**Comment by alandipert** [comment]
:clap: Thanks!

**Pull request merged**
